ingest:
  - source: 'json-collection'
    source_path: '/Users/datomo/git/rag-workshop/maap-chatbot-builder/unibas.json'
    chunk_size: 2000
    chunk_overlap: 200
    subpages: 2
embedding:
    class_name: AdaEmbeddings
vector_store:
    connectionString: ''
    dbName: 'chatter'
    collectionName: 'embedded_content'
    embeddingKey: 'embedding'
    textKey: 'text'
    numCandidates: 150
    minScore: 0.1 
    vectorSearchIndexName: 'vector_index'
llms:
    class_name: Fireworks
    model_name: 'accounts/fireworks/models/mixtral-8x22b-instruct'
    temperature: ''
    top_p: ''
    top_k: ''
