import 'dotenv/config';
import cors from 'cors';  // Import CORS package
import {
    getModelClass,
    getEmbeddingModel,
    getDatabaseConfigInfo
} from '../../../src/yaml_parser/src/LoadYaml.js';
import {
    PreProcessQuery,
    RAGApplicationBuilder,
    Rerank,
    convertBaseEmbeddingsToEmbedder,
    convertBaseModelToChatLlm,
    withQueryPreprocessor,
    withReranker,
} from '../../../src/index.js';

import { MongoClient } from 'mongodb';
import {
    makeDefaultFindContent,
    MakeUserMessageFunc,
    OpenAiChatMessage,
    GenerateUserPromptFunc,
    makeRagGenerateUserPrompt,
    SystemPrompt,
    makeMongoDbConversationsService,
    AppConfig,
    makeApp,
} from 'mongodb-chatbot-server';
import { makeMongoDbEmbeddedContentStore, logger } from 'mongodb-rag-core';

import { CohereReranker } from '../../../src/reranker/cohere-reranker.js';
import { request } from 'node:http';


// Load MAAP base classes
const model = getModelClass();
const embedding_model = getEmbeddingModel();
const { dbName, connectionString, vectorSearchIndexName, minScore, numCandidates } = getDatabaseConfigInfo();

// MongoDB data source for the content used in RAG.
// Generated with the Ingest CLI.
const embeddedContentStore = makeMongoDbEmbeddedContentStore({
    connectionUri: connectionString,
    databaseName: dbName,
});

// Convert MAAP base embeddings to framework's Embedder
// console.log(embedding_model)
const embedder = convertBaseEmbeddingsToEmbedder(embedding_model);

// Convert MAAP base LLM to framework's ChatLlm
console.log(model);
const llm = await convertBaseModelToChatLlm(model);


// Find content in the embeddedContentStore using the vector embeddings
// generated by the embedder.
const findContent = makeDefaultFindContent({
    embedder,
    store: embeddedContentStore,
    findNearestNeighborsOptions: {
        k: 30,
        path: 'embedding',
        indexName: vectorSearchIndexName,
        numCandidates: numCandidates,
        minScore: minScore,
    },
});

// For MAAP team: this shows how to use the withReranker and withQueryPreprocessor
// functions to wrap the findContent function with reranking and preprocessing functionality.

const cohereReranker = null;//new CohereReranker({ modelName: "rerank-v3.5", k: 5 });

const dummyRerank: Rerank = async ({ query, results }) => {
    return { results };
};


const cohereRerank: Rerank = async ({ query, results }) => {
    // Create a map of original results for quick lookup
    const originalResultsMap = new Map(
        results.map(result => [String(result.metadata.id), result])
    );

    // Map to ExtractChunkData format for the reranker
    const mappedResults = results.map(result => ({
        pageContent: result.text,
        metadata: {
            id: String(result.metadata.id),
            uniqueLoaderId: String(result.metadata.uniqueLoaderId),
            source: String(result.metadata.source)
        },
        score: result.score
    }));

    // Get reranked results
    const rerankedDocs = await cohereReranker.reRankDocuments(query, mappedResults);
    
    // Map back while preserving reranked order
    const finalResults = rerankedDocs.map(doc => {
        const originalResult = originalResultsMap.get(doc.metadata.id);
        if (!originalResult) {
            throw new Error(`Could not find original result for id ${doc.metadata.id}`);
        }
        return {
            url: originalResult.url,
            sourceName: originalResult.sourceName,
            text: doc.pageContent,
            tokenCount: originalResult.tokenCount,
            embedding: originalResult.embedding,
            metadata: doc.metadata,
            updated: new Date(),
            score: doc.score
        };
    });

    return { results: finalResults };
};





const dummyPreprocess: PreProcessQuery = async ({ query }) => {
    return { preprocessedQuery: query };
};
const findContentWithRerank = withReranker({ findContentFunc: findContent, reranker: dummyRerank }); // dummyRerank // cohereRerank

const findContentWithRerankAndPreprocess = withQueryPreprocessor({
    findContentFunc: findContentWithRerank,
    queryPreprocessor: dummyPreprocess,
});

// Constructs the user message sent to the LLM from the initial user message
// and the content found by the findContent function.
const makeUserMessage: MakeUserMessageFunc = async function ({
    content,
    originalUserMessage,
}): Promise<OpenAiChatMessage & { role: 'user' }> {
    const chunkSeparator = '~~~~~~';
    const context = content.map((c) => c.text).join(`\n${chunkSeparator}\n`);
    const contentForLlm = `Using the following information, answer the user query.

Information:
${context}

User query: ${originalUserMessage}`;
    return { role: 'user', content: contentForLlm };
};

// Generates the user prompt for the chatbot using RAG
const generateUserPrompt: GenerateUserPromptFunc = makeRagGenerateUserPrompt({
    //findContent: findContentWithRerankwithPreprocess,
    //findContent: findContentWithRerankAndPreprocess,
    findContent: findContent,
    makeUserMessage,
});

// System prompt for chatbot
const systemPrompt: SystemPrompt = {
    role: 'system',
    content: ` You are a friendly human-like chatbot. 
    Use relevant provided context and chat history to answer the query at the end. 
    Answer in full. If you don't know the answer, say that you don't know, don't try to make up an answer. 
    Do not use words like context or training data when responding.
    You can say you do not have all the information but do not indicate that you are not a reliable source.`,
};

// Create MongoDB collection and service for storing user conversations
// with the chatbot.

const mongodb = new MongoClient(connectionString);
const conversations = makeMongoDbConversationsService(mongodb.db(dbName));

// Create the MongoDB Chatbot Server Express.js app configuration
const config: AppConfig = {
    conversationsRouterConfig: {
        llm,
        conversations,
        generateUserPrompt,
        systemPrompt,
    },
    maxRequestTimeoutMs: 30000,
    serveStaticSite: true,
};

const corsOptions = {
    origin: 'http://localhost:3000',
    methods: "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS",
    preflightContinue: false,
    optionsSuccessStatus: 204
}

// Start the server and clean up resources on SIGINT.
const PORT = process.env.PORT || 9000;
const startServer = async () => {
    logger.info('Starting server...');
    const app = await makeApp(config);

    app.use(cors(corsOptions));

    const server = app.listen(PORT, () => {
        logger.info(`Server listening on port: ${PORT}`);
    });

    process.on('SIGINT', async () => {
        logger.info('SIGINT signal received');
        await mongodb.close();
        await embeddedContentStore.close();
        await new Promise<void>((resolve, reject) => {
            server.close((error: any) => {
                error ? reject(error) : resolve();
            });
        });
        process.exit(1);
    });
};

try {
    startServer();
} catch (e) {
    logger.error(`Fatal error: ${e}`);
    process.exit(1);
}
